set-option -ga terminal-overrides ",xterm-256color:Tc"

unbind -a

set-option -g prefix C-a
bind-key C-a send-prefix
setw -g mouse on

bind-key q kill-session
bind-key t new-window
bind-key w kill-window
bind-key h swap-window -t -1 \; last-window
bind-key l swap-window -t +1 \; last-window
bind -n C-k send-keys -R \; send-keys C-l
bind-key 1 select-window -t 0
bind-key 2 select-window -t 1
bind-key 3 select-window -t 2
bind-key 4 select-window -t 3
bind-key 5 select-window -t 4
bind-key 6 select-window -t 5
bind-key 7 select-window -t 6
bind-key 8 select-window -t 7
bind-key 9 select-window -t 8

set-option -g status-bg "#2a2a37"
set-option -g status-fg "#7d7d9b"
set-option -g window-status-current-style "fg=#dcd7ba"
set-option -g status-right-style "fg=#ff5d62"
set-option -g status-left " "
set-option -g status-right "TMUX "
set-option -g window-status-format "» #W"
set-option -g window-status-current-format "» #W"
